# Generated by Django 4.2.1 on 2023-05-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=10, max_digits=20)),
                ('capacidad', models.IntegerField()),
                ('caracteristicas', models.TextField(max_length=500)),
                ('numero', models.IntegerField()),
                ('disponibilidad', models.BooleanField(default=True)),
            ],
        ),
    ]
