# Generated by Django 4.2.1 on 2023-05-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estancia', models.IntegerField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('direccion_factura', models.CharField(max_length=120)),
                ('habitacion', models.IntegerField()),
            ],
        ),
    ]
